notifications:
  email: false
sudo: required
language: ruby
rvm:
  - 2.4.1
bundler_args: --without development:production
cache:
  bundler: true
env:
  - RAILS_ENV=test
services:
  - docker
before_script:
  - ./docker/setup
  - docker-compose up
script:
  - bundle exec rspec
