notifications:
  email: false
sudo: required
language: ruby
rvm:
  - 2.4.2
bundler_args: --without development:production
cache:
  bundler: true
env:
  - RAILS_ENV=test
services:
  - docker
before_script:
  - bundle exec ./docker/setup
  - docker-compose up -d
  - bundle exec rake db:mongoid:create_indexes
script:
  - bundle exec rspec
