:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 5 %>
:verbose: true
:queues:
  - default
  - serialisations
  - thumbnails
  - tmp_cleanup
:schedule:
  tmp_cleanup_job:
    cron: '0 0 * * * *' # Runs every hour
    class: TmpCleanupJob