<%
fail 'No VCAP_SERVICES env' unless ENV.key?('VCAP_SERVICES')
vcap_services = JSON.parse(ENV['VCAP_SERVICES'])
compose_for_mongodb = vcap_services['compose-for-mongodb']
fail 'No compose-for-mongodb service' unless compose_for_mongodb.present?
service_credentials = compose_for_mongodb.first['credentials']
fail 'No MongoDB credentials' unless service_credentials.present?
mongodb_uri = Mongo::URI.new(service_credentials['uri'])
fail 'No MongoDB URI' unless mongodb_uri.present?
%>
production:
  clients:
    default:
      database: <%= mongodb_uri.database %>
      hosts:
      <% mongodb_uri.servers.each do |server| %>
        - <%= server %>
      <% end %>
      options:
        user: <%= mongodb_uri.credentials[:user] %>
        password: <%= mongodb_uri.credentials[:password] %>
        auth_source: <%= mongodb_uri.uri_options['auth_source'] %>
        ssl: <%= mongodb_uri.uri_options['ssl'].to_s %>
        ssl_ca_cert: <%= File.join(Rails.root, 'config', 'compose-for-mongodb-ca.crt') %>
